version: '3'
services:
  backend:
    build: ./backend
    image: backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    # restart: always
    depends_on:
      - postgres
    networks:
      - ponggame
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    # restart: always
    depends_on:
      - backend
    networks:
      - ponggame
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    ports:
      - 5434:5432
    # restart: always
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    networks:
      - ponggame
networks:
  ponggame:
