version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    # restart: always
    depends_on:
      - dev-postgres
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    # restart: always
    depends_on:
      - backend
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    # restart: always
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    networks:
      - lesson
networks:
  lesson:
