version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    # restart: always
    depends_on:
      - backend
    networks:
      - front-tier

  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    # restart: always
    depends_on:
      - database
    networks:
      - front-tier
      - back-tier
    # 新しいバージョンならhealthcheckとdependsonで対応するところ
    command: ["sh", "-c", "./wait-for-postgres.sh database ./docker-entrypoint.sh"]

  database:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    # restart: always
    networks:
      - back-tier
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  postgres-data-volume: