
name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: backend install
        run: yarn --cwd backend install
      - name: backend build
        run: yarn --cwd backend build
      - name: frontend install
        run: yarn --cwd frontend install
      - name: frontend build
        run: yarn --cwd frontend build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: env and docker
        run: |
          echo 'DATABASE_URL="postgresql://udemy:udemy@localhost:5434/udemy?schema=public"' > backend/.env
          docker-compose -f backend/docker-compose.yml up -d
      - name: backend install
        run: yarn --cwd backend install
      - name: backend prisma generate
        run: yarn --cwd backend prisma generate
      - name: backend prisma migrate
        run: yarn --cwd backend prisma migrate dev --name init
      - name: backend test
        run: yarn --cwd backend test:runInBand
      - name: frontend install
        run: yarn --cwd frontend install
      - name: frontend prisma db pull
        run: yarn --cwd frontend prisma db pull
      - name: frontend prisma generate
        run: yarn --cwd frontend prisma generate
      - name: start app
        run: ./start-app.sh
      - name: frontend test
        run: yarn --cwd frontend cypress run
